/* Generated By:JavaCC: Do not edit this line. FPrologConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FPrologConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ATOM = 5;
  /** RegularExpression Id. */
  int VAR = 6;
  /** RegularExpression Id. */
  int MIN = 7;
  /** RegularExpression Id. */
  int MAJ = 8;
  /** RegularExpression Id. */
  int DIG = 9;
  /** RegularExpression Id. */
  int LPAREN = 10;
  /** RegularExpression Id. */
  int RPAREN = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int STOP = 13;
  /** RegularExpression Id. */
  int IMPL = 14;
  /** RegularExpression Id. */
  int PROMPT = 15;
  /** RegularExpression Id. */
  int BANG = 16;
  /** RegularExpression Id. */
  int NOT = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<ATOM>",
    "<VAR>",
    "<MIN>",
    "<MAJ>",
    "<DIG>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\":-\"",
    "\"?-\"",
    "\"!\"",
    "\"\\\\+\"",
  };

}
